-- Top 10 customers by lifetime value
SELECT USER_ID, SUM(AMOUNT) AS LTV
FROM   FACT_ORDERS
GROUP  BY 1
ORDER  BY 2 DESC
LIMIT 10;

-- Revenue by day (last 7)
SELECT DAY, TOTAL_REVENUE
FROM   VW_DAILY_REVENUE
WHERE  DAY >= DATEADD(day, -7, CURRENT_DATE)
ORDER  BY DAY;
