USE SCHEMA PUBLIC;
CREATE OR REPLACE VIEW VW_DAILY_REVENUE AS
SELECT DATE_TRUNC('day', TS) AS DAY,
       SUM(AMOUNT) AS TOTAL_REVENUE
FROM FACT_ORDERS
GROUP BY 1
ORDER BY 1 DESC;

CREATE OR REPLACE VIEW VW_REPEAT_RATE AS
WITH orders_per_user AS (
  SELECT USER_ID, COUNT(*) AS num_orders
  FROM FACT_ORDERS
  GROUP BY USER_ID
)
SELECT ROUND(100 * SUM(CASE WHEN num_orders > 1 THEN 1 ELSE 0 END) / COUNT(*), 2) AS repeat_pct
FROM orders_per_user;
